"""Add date field in Courses

Revision ID: 3bd395b09369
Revises: 2d09a50a7084
Create Date: 2019-02-13 17:00:37.911920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd395b09369'
down_revision = '2d09a50a7084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('conclusion_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'conclusion_date')
    # ### end Alembic commands ###
